name: Local Config
version: 1.0.0
schema: v1

models:
  hfLocalHub: path_to/hf_models
  ollama:
    modelName: gemma3:1b
    url: http://localhost:11434/api/generate
  embeddingModel: sentence-transformers/all-MiniLM-L6-v2
  ollamaEmbeddingModel: bge-m3:latest 

data:
  newsEmbeddings: .\data\embeddings.joblib
  newsCSV: .\data\news_data_dedup.csv
  chromaPath: .\data\chroma_db
  clothesData: .\data\clothes_json.joblib
  faqData: .\data\faq.joblib
  productsChromaPath: .\data\chroma_db_products


completionOptions:
  temperature: 0.7
  maxTokens: 500
